portal_homepage:
    path:     /
    defaults: { _controller: PortalBundle:Default:index }

epic:
    path:     /epic
    defaults: { _controller: PortalBundle:Default:createEpic }

pasta_bella:
    path:     /pasta_bella
    defaults: { _controller: PortalBundle:Default:createPastaBella }
